### ISSUE TITLE
macos-x64, win-x64, alpine-x64 and linux-x64 binaries

### ISSUE THREAD

**Issue by n1ru4l** [yao-pkg/pkg-binaries#10]
Would also be nice to have those over here as pkg-fetch repository is only infrequently maintained.

macos and win binaries must be built without docker buildx as there is no way to emulate that. Fortunately, GitHub actions does have support for both macos and win. Because of that the build should also not take that long and require a custom builder.

**Comment by robertsLando** [comment]
@n1ru4l If you want I could create the tags/releases we spoke about. Are you ok so to have `node10` `node12` `node14` tags?

**Comment by n1ru4l** [comment]
@robertsLando yes!

**Comment by robertsLando** [comment]
Done

**Comment by robertsLando** [comment]
@n1ru4l I have moved the binaries from the old release to the new ones, please give it a check I didn't miss something (except the node13 that I skipped on purpose). Anyway I will also leave there the first release as some users may have scripts pointing there to download the binaries, will remove it in the future maybe or we could keep that for non LTS node versions
