### ISSUE TITLE
fetched-v12.18.1-alpine-ppc64

### ISSUE THREAD

**Issue by asdfugil** [yao-pkg/pkg-binaries#12]
powerpc 64 bit alpine node.js 12.18.1
[fetched-v12.18.1-alpine-ppc64.zip](https://github.com/robertsLando/pkg-binaries/files/5112293/fetched-v12.18.1-alpine-ppc64.zip)

**Comment by robertsLando** [comment]
Keep it here for now so users can download it from here, in next releases we will provide some automated build also for that arch

**Comment by n1ru4l** [comment]
https://hub.docker.com/r/ppc64le/node/tags
