### ISSUE TITLE
Nodejs 16/18 binaries are empty in releases

### ISSUE THREAD

**Issue by kennethpdev** [yao-pkg/pkg-binaries#23]
I like your repo because I saw the arm7 for the Linux node16, but when I look at the releases the said binary does not exist and your build workflow is also failing, maybe that's why. Is there a chance we can fix that and able to produce the right binary?

**Comment by robertsLando** [comment]
@kennethpdev I tried different ways to build nodejs 16/18 on armv7 without success, build never ends, I need to try with an RPI or another armv7 custom runner

**Comment by robertsLando** [comment]
FYI: https://github.com/yao-pkg/pkg-binaries/actions/runs/4142112503/jobs/7162400708

**Comment by kennethpdev** [comment]
@robertsLando thanks for that information, also saw the runner, I think the build was a success but it failed to upload?

**Comment by robertsLando** [comment]
I uploaded it manually, luckily the runner is a custom runner so I have been able to access those files

**Comment by robertsLando** [comment]
Now I fix the upload thing and try to run the nodejs 18 build, should take aproximately 4h

**Comment by kennethpdev** [comment]
> Now I fix the upload thing and try to run the nodejs 18 build, should take aproximately 4h

thanks bro , I appreciate it, will wait for the new build then.

**Comment by robertsLando** [comment]
You welcome 😄

**Comment by robertsLando** [comment]
Had to re-trigger nodejs 18 build cause it stopped with no reason, retried

**Comment by kennethpdev** [comment]
looks like there is a problem with node18 build?

> Error! Error: ENOENT: no such file or directory, open '/tmp/pkg.3f16f24465298a81b7d02149/node/out/Release/node'
Error: Process completed with exit code 2.

maybe you can do node16 for now.
