### ISSUE TITLE
[action] Automated builds

### ISSUE THREAD

**Issue by robertsLando** [yao-pkg/pkg-binaries#5]
This issue is used to trigger actions to build pkg binaries using github actions.

Usage: `<arch> <nodeVersion> <os>`

- `arch`: arm32v6 | arm32v7 | arm64
- `node`: node<version>
- `os`: linux | alpine

**Comment by robertsLando** [comment]
Another test

**Comment by robertsLando** [comment]
arm32v7 node14 linux

**Comment by robertsLando** [comment]
arm32v7 node14 linux

**Comment by robertsLando** [comment]
arm32v7 node14 linux

**Comment by robertsLando** [comment]
arm32v7 node14 linux

**Comment by robertsLando** [comment]
arm32v7 node14 linux

**Comment by robertsLando** [comment]
arm32v7 node14 linux

**Comment by robertsLando** [comment]
arm32v7 node14 linux

**Comment by robertsLando** [comment]
arm32v7 node14 linux

**Comment by robertsLando** [comment]
arm32v7 node14 linux

**Comment by robertsLando** [comment]
arm32v7 node14 linux

**Comment by robertsLando** [comment]
arm32v7 node14 linux

**Comment by robertsLando** [comment]
arm64 node14 linux

**Comment by robertsLando** [comment]
arm64 node14 linux

**Comment by robertsLando** [comment]
arm64 node14 linux

**Comment by robertsLando** [comment]
arm64 node14 linux

**Comment by robertsLando** [comment]
arm64 node12 linux

**Comment by robertsLando** [comment]
arm32v7 node12 linux

**Comment by robertsLando** [comment]
arm64 node13 linux

**Comment by robertsLando** [comment]
arm32v7 node13 linux

**Comment by robertsLando** [comment]
arm64 node12 alpine

**Comment by robertsLando** [comment]
arm32v7 node12 alpine

**Comment by robertsLando** [comment]
arm64 node12 linux

**Comment by robertsLando** [comment]
arm32v7 node12 linux

**Comment by robertsLando** [comment]
arm64 node14 linux

**Comment by robertsLando** [comment]
arm32v7 node14 linux

**Comment by robertsLando** [comment]
arm64 node14 linux

**Comment by robertsLando** [comment]
arm64 node12 linux

**Comment by n1ru4l** [comment]
arm64 node12 linux

**Comment by n1ru4l** [comment]
arm64 node12 linux

**Comment by n1ru4l** [comment]
arm32v7 node12 linux
